torchrun --standalone --nproc_per_node=1 train_cirilla.py \
  --input_bin "data/fineweb10B/fineweb_train_*.bin" \
  --input_val_bin "data/fineweb10B/fineweb_val_*.bin" \
  --output_dir pylog124M \
  --batch_size 16 \
  --grad_accumulation_steps 16 \
  --sequence_length 1024 \
  --val_loss_every 128 \
  --val_batch_size 32 \
  --num_iterations 4768 \
  --weight_decay 0.01 \
  --learning_rate 0.0018 \
  --warmup_iters 256 \
  --warmdown_iters 1024 \
